// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGame():Promise<void>;

export function LoadPlayers():Promise<void>;

export function LoadTeamPlayers():Promise<void>;

export function LoadTeams():Promise<void>;
