// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGame() {
  return window['go']['backend']['Game']['CreateGame']();
}

export function LoadPlayers() {
  return window['go']['backend']['Game']['LoadPlayers']();
}

export function LoadTeamPlayers() {
  return window['go']['backend']['Game']['LoadTeamPlayers']();
}

export function LoadTeams() {
  return window['go']['backend']['Game']['LoadTeams']();
}
